const asyncActions = [
  'DOWNLOAD_INI_FILE',
  'CHANGE_GAME_DIRECTORY',
  'RETRIEVE_GAME_LIST',
  'DOWNLOAD_TRANSLATION_UPDATE',
  'INSTALL_UPDATE',
  'UNINSTALL_TRANSLATION',
  'DOWNLOAD_TRANSLATION_PROGRESS'
];

export default asyncActions;
